### PR TITLE
moved tableflip up to available plugins

### PR DESCRIPTION
**Pull request by matthewtrask**
Added @elstamey's table flip plugin to the list of available plugins.

### CODE REVIEW

**Comment by elstamey** [comment]
:fireworks: :tada: :balloon: :fireworks: :tada: :balloon: :fireworks: :tada: :balloon:

**Comment by matthewtrask** [comment]
@svpernova09 looks like @elstamey is good with this.

**Comment by elstamey** [comment]
:+1: definitely.  I'm going to be famous!  :P

**Comment by svpernova09** [comment]
Feel free to merge and deploy 

-- 
- Joe Ferguson
  JoeFerguson.me
  MemphisPHP.org

**Comment by matthewtrask** [comment]
Will merge. Not sure how to deploy

**Comment by svpernova09** [comment]
Run publish.sh

-- 
- Joe Ferguson
  JoeFerguson.me
  MemphisPHP.org

**Pull request merged**
